# boards schema

# --- !Ups

CREATE TABLE States (
  Id SERIAL PRIMARY KEY,
  State BLOB
);

CREATE TABLE Boards (
  Id CHAR(5) PRIMARY KEY,
  GameId INT NOT NULL,
  StateId BIGINT UNSIGNED,
  IsPublic BOOLEAN NOT NULL,
  Status INT UNSIGNED,
  RematchBoardId CHAR(5),
  ParentBoardId CHAR(5),
  ParentStateId BIGINT UNSIGNED,
  FOREIGN KEY StateFk (StateId) REFERENCES States(Id) ON DELETE RESTRICT,
  FOREIGN KEY RematchBoardFk (RematchBoardId) REFERENCES Boards(Id) ON DELETE SET NULL,
  FOREIGN KEY ParentBoardFk (ParentBoardId) REFERENCES Boards(Id) ON DELETE SET NULL,
  FOREIGN KEY ParentStateFk (ParentStateId) REFERENCES States(Id) ON DELETE SET NULL
);

CREATE TABLE Users (
  Id SERIAL PRIMARY KEY,
  Username TEXT NOT NULL,
  Password TEXT NOT NULL
);

CREATE TABLE Friendships (
  Id SERIAL PRIMARY KEY,
  User1Id BIGINT UNSIGNED NOT NULL,
  User2Id BIGINT UNSIGNED NOT NULL,
  Date DATETIME NOT NULL,
  FOREIGN KEY User1Fk (User1Id) REFERENCES Users(Id) ON DELETE CASCADE,
  FOREIGN KEY User2Fk (User2Id) REFERENCES Users(Id) ON DELETE CASCADE
);

CREATE TABLE Invites (
  Id SERIAL PRIMARY KEY,
  InviterId BIGINT UNSIGNED NOT NULL,
  InviteeId BIGINT UNSIGNED NOT NULL,
  BoardId CHAR(5) NOT NULL,
  FOREIGN KEY InviterFk (InviterId) REFERENCES Users(Id) ON DELETE CASCADE,
  FOREIGN KEY InviteeFk (InviteeId) REFERENCES Users(Id) ON DELETE CASCADE,
  FOREIGN KEY BoardFk (BoardId) REFERENCES Boards(Id) ON DELETE CASCADE
);

CREATE TABLE Players (
  Id SERIAL PRIMARY KEY,
  UserId BIGINT UNSIGNED,
  BoardId CHAR(5) NOT NULL,
  TurnOrder INT NOT NULL,
  IsOwner BOOLEAN NOT NULL,
  Time INT NOT NULL,
  ResignationOffered BOOLEAN NOT NULL,
  DrawOffered BOOLEAN NOT NULL,
  FOREIGN KEY UserFk (UserId) REFERENCES Users(Id) ON DELETE SET NULL,
  FOREIGN KEY BoardFk (BoardId) REFERENCES Boards(Id) ON DELETE CASCADE
);

# --- !Downs

DROP TABLE States;
DROP TABLE Boards;
DROP TABLE Users;
DROP TABLE Friendships;
DROP TABLE Invites;
DROP TABLE Players;